{
    "name": "New Estate",
    "version": "1.0",
    "summary": "Property Selling platform",
    "sequence": 10,
    "description": """""",
    "category": "Sales",
    "website": "",
    "depends": ["base"],
    "data": [
        "security/ir.model.access.csv",
        "views/estate_property_views.xml",
        "views/estate_menus.xml",
    ],
    "demo": [],
    "application": True,
    "installable": True,
    "assets": {},
    "author": "Chengyan(CHWAN)",
    "license": "LGPL-3",
}
