{
    "name": "New Estate",
    "version": "1.0",
    "summary": "Property Selling platform",
    "sequence": 10,
    "description": """""",
    "category": "Sales",
    "website": "",
    "depends": ["base"],
    "data": [],
    "demo": [],
    "application": True,
    "installable": True,
    "assets": {},
    "author": "Chengyan(CHWAN)",
    "license": "LGPL-3",
}
